"""
Gating tests for Phase 4 tags (the multi-file-write safety seam).

Per docs/decisions.md Q004-1..4 + DESIGN:437-454:
- `cairn tags`: list tags with counts, sorted frequency-desc then alpha; read-only.
- `cairn tag rename <old> <new>`: rewrite the tag in every note's frontmatter
  (NOT inline #old). Collision (new exists) -> refuse. Zero matches -> refuse.
  Per-file atomic write; best-effort cross-file; a failed note is skipped and
  reported; ONE auto-commit of the successfully-rewritten notes.
- `cairn tag remove <tag>`: remove the tag from every note's frontmatter.
- `indexes/tags.md`: generated by reindex, one section per tag (alpha) with
  backlinks; committed.

The seam: tag rename touches MANY files before a single auto-commit. The
pre-commit scan still runs on that commit, so no rewrite can land a secret.
"""

import os
import subprocess
from pathlib import Path

from cairn.frontmatter import write_frontmatter, read_frontmatter


def _run(vault, args):
    return subprocess.run(
        ["cairn"] + args, cwd=str(vault),
        capture_output=True, text=True, env=os.environ.copy(),
    )


def _git(args, vault):
    return subprocess.run(["git"] + args, cwd=str(vault),
                          capture_output=True, text=True, env=os.environ.copy())


def _note(vault, name, fm, body=""):
    (vault / "notes" / name).write_text(write_frontmatter(fm) + body)
    _git(["add", "notes"], vault)
    _git(["commit", "-m", "seed"], vault)


FM = {
    "id": "z", "title": "T", "type": "note", "status": "active", "project": "",
    "tags": ["x"], "created": "2026-08-09", "updated": "2026-08-09",
    "cairn_version": 1, "moc": "", "source": "", "source_url": "",
}


class TestTagsList:
    def test_lists_tags_with_counts_sorted(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["rare"]), "x\n")
        _note(tmp_vault, "b.md", dict(FM, id="b1", title="B", tags=["common"]), "x\n")
        _note(tmp_vault, "c.md", dict(FM, id="c1", title="C", tags=["common", "alpha"]), "x\n")
        r = _run(tmp_vault, ["tags"])
        assert r.returncode == 0, r.stderr
        # common (2) appears before rare (1) and alpha (1) - frequency desc
        out = r.stdout
        assert out.index("common") < out.index("rare")

    def test_tags_is_read_only(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["x"]), "body\n")
        before = _git(["rev-parse", "HEAD"], tmp_vault).stdout.strip()
        _run(tmp_vault, ["tags"])
        after = _git(["rev-parse", "HEAD"], tmp_vault).stdout.strip()
        assert before == after

    def test_ignores_inline_hashtag(self, tmp_vault):
        # Inline #tag in body is prose; only frontmatter tags count.
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["frontmatter-tag"]), "see #body-tag here\n")
        r = _run(tmp_vault, ["tags"])
        assert "frontmatter-tag" in r.stdout
        assert "body-tag" not in r.stdout


class TestTagRename:
    def test_renames_across_notes_frontmatter_only(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["old", "keep"]), "see #old inline\n")
        _note(tmp_vault, "b.md", dict(FM, id="b1", title="B", tags=["old"]), "x\n")
        r = _run(tmp_vault, ["tag", "rename", "old", "new"])
        assert r.returncode == 0, r.stderr
        fa, _ = read_frontmatter(tmp_vault / "notes" / "a.md")
        fb, _ = read_frontmatter(tmp_vault / "notes" / "b.md")
        assert "new" in fa["tags"] and "old" not in fa["tags"] and "keep" in fa["tags"]
        assert fb["tags"] == ["new"]
        # inline #old is NOT rewritten (frontmatter-only mutation, Q004-3)
        assert "#old inline" in (tmp_vault / "notes" / "a.md").read_text()

    def test_normalizes_old_and_new(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["cfg/old"]), "x\n")
        r = _run(tmp_vault, ["tag", "rename", "CFG/Old", "CFG/New"])
        assert r.returncode == 0, r.stderr
        fa, _ = read_frontmatter(tmp_vault / "notes" / "a.md")
        assert "cfg/new" in fa["tags"]

    def test_collision_refuses(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["old"]), "x\n")
        _note(tmp_vault, "b.md", dict(FM, id="b1", title="B", tags=["existing"]), "x\n")
        r = _run(tmp_vault, ["tag", "rename", "old", "existing"])
        assert r.returncode != 0, "renaming onto an existing tag must refuse"
        # nothing changed
        fa, _ = read_frontmatter(tmp_vault / "notes" / "a.md")
        assert fa["tags"] == ["old"]

    def test_zero_matches_refuses(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["real"]), "x\n")
        r = _run(tmp_vault, ["tag", "rename", "nonexistent", "other"])
        assert r.returncode != 0, "renaming a tag that matches nothing must refuse"

    def test_note_with_both_old_and_new_no_duplicate(self, tmp_vault):
        # A note carrying both old and new: rename old->new yields a single new
        # (merge), not [new, new]. Collision check excludes notes that also
        # carry old, so the rebuild must dedup.
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["old", "new"]), "x\n")
        r = _run(tmp_vault, ["tag", "rename", "old", "new"])
        assert r.returncode == 0, r.stderr
        fa, _ = read_frontmatter(tmp_vault / "notes" / "a.md")
        assert fa["tags"] == ["new"], f"expected single 'new', got {fa['tags']}"


    def test_single_commit_of_rewritten_notes(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["old"]), "x\n")
        _note(tmp_vault, "b.md", dict(FM, id="b1", title="B", tags=["old"]), "x\n")
        _note(tmp_vault, "c.md", dict(FM, id="c1", title="C", tags=["other"]), "x\n")
        _run(tmp_vault, ["tag", "rename", "old", "new"])
        # exactly one new commit
        log = _git(["rev-list", "--count", "HEAD~1..HEAD"], tmp_vault).stdout.strip()
        assert log == "1"

    def test_partial_failure_skips_and_reports(self, tmp_vault):
        # Two notes carry the tag; one is malformed so it cannot be rewritten.
        _note(tmp_vault, "good.md", dict(FM, id="g1", title="Good", tags=["old"]), "x\n")
        (tmp_vault / "notes" / "bad.md").write_text("no frontmatter at all\n")
        _git(["add", "notes/bad.md"], tmp_vault)
        _git(["commit", "-m", "seed bad"], tmp_vault)
        r = _run(tmp_vault, ["tag", "rename", "old", "new"])
        # good.md was rewritten; bad.md was skipped and reported
        fg, _ = read_frontmatter(tmp_vault / "notes" / "good.md")
        assert "new" in fg["tags"]
        combined = r.stdout + r.stderr
        assert "bad" in combined.lower(), "the failed note must be named in the report"


class TestTagRemove:
    def test_removes_tag_from_all_notes(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["gone", "keep"]), "x\n")
        _note(tmp_vault, "b.md", dict(FM, id="b1", title="B", tags=["gone"]), "x\n")
        r = _run(tmp_vault, ["tag", "remove", "gone"])
        assert r.returncode == 0, r.stderr
        fa, _ = read_frontmatter(tmp_vault / "notes" / "a.md")
        fb, _ = read_frontmatter(tmp_vault / "notes" / "b.md")
        assert fa["tags"] == ["keep"]
        assert fb["tags"] == []

    def test_zero_matches_refuses(self, tmp_vault):
        _note(tmp_vault, "a.md", dict(FM, id="a1", title="A", tags=["real"]), "x\n")
        r = _run(tmp_vault, ["tag", "remove", "nonexistent"])
        assert r.returncode != 0
